# Generated by Django 2.0.3 on 2018-03-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phoone',
            new_name='phone',
        ),
    ]
