# Generated by Django 2.0.3 on 2018-03-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobtag',
            table='job_tag',
        ),
    ]
