# Generated by Django 2.0.3 on 2018-05-11 14:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180411_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='difficulty_level',
            field=models.ForeignKey(default=2, on_delete='SET_DEFAULT', to='core.DifficultyLevel'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=core.models.default_start_time),
        ),
    ]
