# Generated by Django 2.0.3 on 2018-03-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
