# Generated by Django 2.0.3 on 2018-03-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180320_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
