# Generated by Django 2.1.4 on 2019-01-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190104_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='set_number',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
