# Generated by Django 2.1.4 on 2019-01-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190107_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='set_number',
            field=models.CharField(max_length=2),
        ),
    ]
