# Generated by Django 2.1.7 on 2019-05-19 11:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190107_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='difficulty_level',
            field=models.ForeignKey(default=core.models.get_default_difficulty, on_delete='SET_DEFAULT', to='core.DifficultyLevel'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=core.models.get_default_publish_date),
        ),
        migrations.AlterField(
            model_name='post',
            name='set_number',
            field=models.CharField(default=core.models.get_default_number, max_length=2),
        ),
    ]
