# Generated by Django 2.0.3 on 2018-03-14 22:39

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=60, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=165, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'title',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificulty_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, null=True)),
                ('url', models.URLField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=70, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=280)),
                ('slug', models.SlugField(max_length=280, unique_for_date='publish')),
                ('url', models.URLField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('set_number', models.CharField(max_length=2)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Public', 'Public')], default='Draft', max_length=20)),
                ('publish', models.DateTimeField(default=datetime.datetime.now)),
                ('tease', models.TextField(blank=True, help_text='Concise text suggested. Does not appear in RSS feed.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=60, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=165, null=True)),
                ('active', models.CharField(choices=[('Draft', 'Draft'), ('Public', 'Public')], default='Active', max_length=20)),
                ('original_author', models.CharField(blank=True, max_length=250)),
                ('original_author_handle', models.CharField(blank=True, max_length=250)),
                ('original_author_url', models.URLField(blank=True, max_length=250)),
                ('thumb_image', models.ImageField(blank=True, upload_to='thumbs/')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete='SET_DEFAULT', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='pages.Category')),
                ('difficulty_level', models.ForeignKey(on_delete='SET_DEFAULT', to='pages.DifficultyLevel')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'posts',
                'ordering': ('-publish',),
                'get_latest_by': 'publish',
            },
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('Article', 'Article'), ('Twitter', 'Twitter'), ('Video', 'Video'), ('Podcast', 'Podcast')], default='Article', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.ForeignKey(on_delete='SET_DEFAULT', to='pages.PostType'),
        ),
    ]
