# Generated by Django 2.0.3 on 2018-03-15 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180314_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='difficultylevel',
            old_name='dificulty_level',
            new_name='difficulty_level',
        ),
    ]
