# Generated by Django 2.0.1 on 2018-02-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180206_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='original_url',
            new_name='url',
        ),
    ]
