# Generated by Django 2.0.3 on 2018-03-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20180315_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficultylevel',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='active',
            field=models.CharField(choices=[('dead', 'Dead'), ('active', 'Active')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('public', 'Public')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='posttype',
            name='post_type',
            field=models.CharField(choices=[('article', 'Article'), ('twitter', 'Twitter'), ('video', 'Video'), ('podcast', 'Podcast')], default='article', max_length=20),
        ),
    ]
