# Generated by Django 2.0.1 on 2018-02-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20180225_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumb_image',
            field=models.ImageField(blank=True, default=False, upload_to='thumbs/'),
            preserve_default=False,
        ),
    ]
