# Generated by Django 2.0.3 on 2018-03-15 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20180315_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettercontact',
            name='date_subscribed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newslettercontact',
            name='date_unsubscribed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslettercontact',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newslettercontact',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='newslettercontact',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=70, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newslettercontact',
            name='ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tease',
            field=models.CharField(blank=True, help_text='Concise text suggested. Does not appear in RSS feed.', max_length=280),
        ),
    ]
