# Generated by Django 2.0.1 on 2018-03-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20180225_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Active'), (1, 'Active')], default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=280),
        ),
    ]
