# Generated by Django 2.0.3 on 2018-03-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20180306_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, null=True)),
                ('url', models.URLField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='posttype',
            name='post_type',
            field=models.IntegerField(choices=[(0, 'Article'), (1, 'Twitter'), (2, 'Video'), (3, 'Podcast')], default=0),
        ),
    ]
