# Generated by Django 2.0.3 on 2018-03-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20180315_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettercontact',
            options={'ordering': ('-date_subscribed',), 'verbose_name': 'Newsletter Contact', 'verbose_name_plural': 'Newsletter Contacts'},
        ),
        migrations.AlterModelTable(
            name='newslettercontact',
            table='newsletter_contacts',
        ),
    ]
